  version: '3.8'
  services:
      flask-app:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "5000:5000"
        environment:
          - FLASK_ENV=development
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:5000"]
          interval: 30s
          timeout: 10s
          retries: 3
