version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-app:latest
    environment:
      - FLASK_ENV=development
    secrets:
      - db_user
      - db_password
      - db_name
      - db_host
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:5000"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
    deploy:
      replicas: 6
      placement:
        max_replicas_per_node: 2
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    networks:
      - swarm-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-stack.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
    networks:
      - swarm-network

  db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    secrets:
      - db_user
      - db_password
      - db_name
    networks:
      - swarm-network

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - swarm-network

volumes:
  db_data:
  portainer_data:

networks:
  swarm-network:
    driver: overlay

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true
  db_host:
    external: true